site_name: Pixisoft Documentation
site_description: Document String tool for Emacs
site_url: https://pixisoft.github.io/
site_author: pixisoft.tw@gmail.com
site_favicon: etc/favicon.ico

nav:
  - Home:
    - Overview: README.md
  - UnityAS:
    - Afterimage: UnityAS/Afterimage/README.md
    - Inspect_Ini: UnityAS/Inspect_Ini/README.md
    - Inspect_Json: UnityAS/Inspect_Json/README.md
    - Inspect_Xml: UnityAS/Inspect_Xml/README.md
    - Inspect_Yaml: UnityAS/Inspect_Yaml/README.md
    - NovBundle: UnityAS/NovBundle/README.md
    - PackageExporter: UnityAS/PackageExporter/README.md
    - sHierarchy: UnityAS/sHierarchy/README.md
    - WatchLog: UnityAS/WatchLog/README.md

extra_css:
  - _stylesheets/extra.css

theme:
  name: 'rtd-dropdown'
  logo: etc/logo.png
  favicon: etc/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Pixisoft
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pixisoft

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - meta
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - rss

google_analytics:
  - UA-165661257-1
  - auto
